[features]
seeds = false
skip-lint = false
[programs.localnet]
got_a_min = "3113AWybUqHaSKaEmUXnUFwXu4EUp1VDpqQFCvY7oajN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/pmd/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g"
# test-filter = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g"
echo-script = "echo 'Hello world!'"
